// <auto-generated />
namespace CapStonePhase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class refactoredmethodstabletoobtainalistofmethodsinStudent_Lectures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactoredmethodstabletoobtainalistofmethodsinStudent_Lectures));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221534443_refactored methods table to obtain a list of methods in Student_Lectures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
