// <auto-generated />
namespace CapStonePhase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedunnecessarytablesandcolumnsandcreatedabytecolumninstudent_lecturesandlecturestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedunnecessarytablesandcolumnsandcreatedabytecolumninstudent_lecturesandlecturestable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711141543414_removed unnecessary tables and columns and created a byte column in student_lectures and lectures table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
