// <auto-generated />
namespace CapStonePhase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedstringcolumnstogetCSVvaluesofmethodnamesandtheirrespectivereturnvalues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedstringcolumnstogetCSVvaluesofmethodnamesandtheirrespectivereturnvalues));
        
        string IMigrationMetadata.Id
        {
            get { return "201711142119195_added string columns to get CSV values of method names and their respective return values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
