// <auto-generated />
namespace CapStonePhase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdStudentsLecturesInstructorsandStudents_Lecturesmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdStudentsLecturesInstructorsandStudents_Lecturesmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201710131403558_created Students, Lectures, Instructors, and Students_Lectures models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
