// <auto-generated />
namespace CapStonePhase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedcodefiletextcolumnsforstudent_LecturesandLecturesmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcodefiletextcolumnsforstudent_LecturesandLecturesmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201711141646072_added codefiletext columns for student_Lectures and Lectures model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
