// <auto-generated />
namespace CapStonePhase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedthewarningcolumnnametoNumberOfWarnings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedthewarningcolumnnametoNumberOfWarnings));
        
        string IMigrationMetadata.Id
        {
            get { return "201710231543491_changed the warning column name to NumberOfWarnings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
