// <auto-generated />
namespace CapStonePhase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class refactoredbytecolumnstostringcolumnsforfilenames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactoredbytecolumnstostringcolumnsforfilenames));
        
        string IMigrationMetadata.Id
        {
            get { return "201711141604094_refactored byte columns to string columns for file names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
