// <auto-generated />
namespace CapStonePhase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdaUnitTestmodelforinstructors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdaUnitTestmodelforinstructors));
        
        string IMigrationMetadata.Id
        {
            get { return "201711101619325_created a UnitTest model for instructors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
