// <auto-generated />
namespace CapStonePhase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removinglectureidfrommstudentmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removinglectureidfrommstudentmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201710171352538_removing lectureid fromm student model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
