// <auto-generated />
namespace CapStonePhase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedacolumninstudentLecturestokeeptrackofwhatmethodsareneededtobeincludedinthecode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedacolumninstudentLecturestokeeptrackofwhatmethodsareneededtobeincludedinthecode));
        
        string IMigrationMetadata.Id
        {
            get { return "201711141739166_added a column in studentLectures to keep track of what methods are needed to be included in the code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
