// <auto-generated />
namespace CapStonePhase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdforeignKeysfromStudents_LecturestoStudentsandtoLectures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdforeignKeysfromStudents_LecturestoStudentsandtoLectures));
        
        string IMigrationMetadata.Id
        {
            get { return "201710131410069_created foreignKeys from Students_Lectures to Students and to Lectures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
