// <auto-generated />
namespace CapStonePhase2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdamethodmodelwithmethodnamereturnvalueandlectureforeignKeycolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdamethodmodelwithmethodnamereturnvalueandlectureforeignKeycolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201711202057258_created a method model with methodname, returnvalue, and lecture foreignKey columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
